### PR TITLE
introduce ILinearSolver interface

### PR DESCRIPTION
**Pull request by EduardBargues**

### CODE REVIEW

**Comment by wo80** [comment]
Iterative solver test works:
```c#
using MathNet.Numerics.LinearAlgebra;
using MathNet.Numerics.LinearAlgebra.Double;
using MathNet.Numerics.LinearAlgebra.Double.Solvers;
using MathNet.Numerics.LinearAlgebra.Solvers;

internal class IterativeSolverForTesting : ILinearSolver
{
    private readonly Matrix<double> matrix;
    private IIterativeSolver<double> solver => new TFQMR(); // Performs better than BiCgStab in this case.

    private Iterator<double> iterator;
    private IPreconditioner<double> preconditioner;

    public IterativeSolverForTesting(Matrix<double> matrix, double tolerance = 1e-5, int maxIterations = 100)
    {
        this.matrix = matrix;

        iterator = new Iterator<double>(
            new IterationCountStopCriterion<double>(maxIterations),
            new ResidualStopCriterion<double>(tolerance)
        );

        preconditioner = new DiagonalPreconditioner(); // Fails with BiCgStab.
        //preconditioner = new ILU0Preconditioner(); // Ok with BiCgStab.
    }

    public Vector<double> Solve(Vector<double> input)
    {
        var result = new DenseVector(input.Count);

        if (input.InfinityNorm() < 1e-12)
        {
            // Math.NET bug: https://github.com/mathnet/mathnet-numerics/issues/720
            return result;
        }

        solver.Solve(matrix, input, result, iterator, preconditioner);

        return result;
    }
}
```

**Comment by wo80** [comment]
EDIT: please ignore the following. I think the current interface design is good and should work well with other solver implementations (just tested with CSparse.NET).

> I am wondering, if there should be a separation between solver and data. So the interface could be
> ```
> public interface ILinearSolver
> {
>     void Solve(Matrix<double> matrix, Vector<double> input, Vector<double> result);
> }
> ```
> The solver setup would then look something like
> ```
> static Vector<double> Reaction(Vector<double> u) => new DenseVector(2) { [0] = u[0], [1] = u[0] + 2 * u[1] };
> static Matrix<double> Stiffness(Vector<double> u) => new DenseMatrix(2, 2) { [0, 0] = 1, [1, 0] = 1, [1, 1] = 2 };
> DenseVector force = new DenseVector(2) { [0] = 1, [1] = 3 };
> 
> NonLinearSolver Solver = NonLinearSolver.Builder
>     .UseLinearSolver(new LinearSolverForTesting())
>     .Solve(2, Reaction, Stiffness)
>     .Under(force)
>     .UsingArcLengthScheme(radius)
>     .Build();
> ```

**Comment by epsi1on** [comment]
I've forked this repo (available [here](https://github.com/epsi1on/NonLinearEquationsSolver)) and am working on for supporting CSparse and using double array instead of Vector, once done will make it as pull request to main repo. I put several hours today to convert all `Vector<double>` to `double[]` and `Matrix<double>` to `CSparse.Double.SparseMatrix`. Let me to finish my work, then I'll let you know.

**Review by wo80 — APPROVED** [review]

**Review by epsi1on — APPROVED** [review]

**Comment by epsi1on** [comment]
Is it OK to continue?

**Comment by epsi1on** [comment]
I made two edits on `ILinearSolver`, added `Initialize()` method and `IsInitialized{get;}` property, also a new Solve method `void Solve(double[] b, double[] x);` where `b` is input, and `x` is output

**Pull request merged**
